pilot:
  autoscaleEnabled: true
  autoscaleMin: 3
  autoscaleMax: 8
  replicaCount: 3
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi

gateways:
  istio-ingressgateway:
    autoscaleEnabled: true
    autoscaleMin: 3
    autoscaleMax: 10
    replicaCount: 3
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true

global:
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
